### ISSUE TITLE
Redis client required even for in-memory-only cache.

### ISSUE THREAD

**Issue by nethermead** [englercj/mongoose-cache-manager#5]
An error is thrown in the redis module when it attempts to connect to localhost using the following options (as specified in your readme).  

mongooseCache(mongoose, {
                    cache: true,
                    ttl: 60,
                    store: 'memory',
                    prefix: 'cache'
                });

Here's the error:

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/Users/alangton/Documents/Dev/goroost/node/NodeRoostAPI/node_modules/mongoose-cache-manager/node_modules/redis/index.js:196:24)
    at Socket.RedisClient.install_stream_listeners.stream.on.self.should_buffer (/Users/alangton/Documents/Dev/goroost/node/NodeRoostAPI/node_modules/mongoose-cache-manager/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:95:17)
    at Socket._destroy.self._writableState.errorEmitted (net.js:441:14)
    at process._tickDomainCallback (node.js:486:13)

**Comment by englercj** [comment]
https://github.com/englercj/mongoose-cache-manager/issues/4#issuecomment-68734680
